name: sherlock
dependencies:
  - python=3.7
  - numpy>1.17
  - scikit-learn>0.19.1
  - networkx>2.1
  - scipy>1.1.0
  - matplotlib>2.2.2
  - seaborn>0.9.0
  - plotly
  - pandas>1.0.1
  - conda-forge::dash
  - conda-forge::dash-bootstrap-components
